### ISSUE TITLE
Remote database with optional local version

### ISSUE THREAD

**Issue by Akahadaka** [goodwilltyping/OpenFight#3]
Use the browsers ability to create **local storage** for a website to save a local copy of the JSON database. If an internet connection is available, the local database will automatically update. If no internet connection is detected, the app can run successfully on local storage only.

**NOTE:** We cannot create a physical file locally to store the database in. This would be a security issue as website would then have the power to modify a users filesystem.

**Comment by Akahadaka** [comment]
Currently this is being saved to local storage in 4 lists, one for each column; Fighter, Power, Weapon and Location. We may have to change this later if we decide to extend the database to support different languages, or something.

**Comment by goodwilltyping** [comment]
Is it possible to keep this local, generated file permanently?
